config/routes.rb
Rails.application.routes.draw do
  resources :ordem_servicos
  resources :equipes
  resources :veiculos
  resources :funcionarios
  resources :parts
  resources :servicos
  resources :clientes

  devise_for :users
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    get '/users/sign_in', to: 'devise/sessions#new'
    post '/users/sign_in', to: 'devise/sessions#create'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  get 'home/dashboard'
  root 'home#dashboard'

  resources :ordem_servicos do
    member do
      post 'concluir'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :ordem_servicos, dependent: :destroy
    has_many :veiculos, dependent: :destroy

    
  def self.total_clientes
    count
  end
  
end

app/models/equipe.rb
class Equipe < ApplicationRecord
    has_many :funcionarios, dependent: :destroy
    has_many :ordem_servicos, dependent: :destroy
end
  

app/models/funcionario.rb
class Funcionario < ApplicationRecord
    belongs_to :equipe

    def self.total_funcionarios
        count
    end

end

app/models/ordem_servico.rb
class OrdemServico < ApplicationRecord
    belongs_to :veiculo
    belongs_to :cliente
    belongs_to :equipe
    belongs_to :servico
    belongs_to :part

    
    
    def valor_total
        part.preco + servico.valor
    end

    def self.total_ordens_concluidas
        where(concluida: true).count
    end

end

app/models/part.rb
class Part < ApplicationRecord

    has_many :ordem_servicos, dependent: :destroy

    def self.valor_total_em_estoque
        Part.sum('preco * quantidade')
    end
    def self.total_em_estoque
        Part.sum(:quantidade)
    end
end

app/models/servico.rb
class Servico < ApplicationRecord
    has_many :ordem_servicos, dependent: :destroy

    def self.total_servicos
        count
    end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
    belongs_to :cliente
    has_many :ordem_servicos, dependent: :destroy
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
  before_action :set_equipe, only: %i[ show edit update destroy ]

  # GET /equipes or /equipes.json
  def index
    @equipes = Equipe.all
  end

  # GET /equipes/1 or /equipes/1.json
  def show
  end

  # GET /equipes/new
  def new
    @equipe = Equipe.new
  end

  # GET /equipes/1/edit
  def edit
    @equipes = Equipe.find(params[:id])
  end

  # POST /equipes or /equipes.json
  def create
    @equipe = Equipe.new(equipe_params)

    respond_to do |format|
      if @equipe.save
        format.html { redirect_to @equipe, notice: "Equipe was successfully created." }
        format.json { render :show, status: :created, location: @equipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipes/1 or /equipes/1.json
  def update
    respond_to do |format|
      if @equipe.update(equipe_params)
        format.html { redirect_to equipe_url(@equipe), notice: "Equipe was successfully updated." }
        format.json { render :show, status: :ok, location: @equipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipes/1 or /equipes/1.json
  def destroy
    @equipe.destroy!

    respond_to do |format|
      format.html { redirect_to equipes_url, notice: "Equipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipe
      @equipe = Equipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipe_params
      params.require(:equipe).permit(:nome, :descricao)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    
    @quantidade_em_estoque = Part.total_em_estoque
    @total_clientes = Cliente.total_clientes
    @total_servicos = Servico.total_servicos
    @total_ordens_concluidas = OrdemServico.total_ordens_concluidas
    @total_funcionarios = Funcionario.total_funcionarios
    @valor_total_em_estoque = Part.valor_total_em_estoque

  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]

  # GET /parts or /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1 or /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts or /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to part_url(@part), notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1 or /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to part_url(@part), notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1 or /parts/1.json
  def destroy
    @part.destroy!

    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:nome, :quantidade, :preco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ordem_servicos_helper.rb
module OrdemServicosHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/equipes/_equipe.html.erb
<div id="<%= dom_id equipe %>" class="design-info">

  <p>
    <strong>Nome:</strong>
    <%= equipe.nome %>
  </p>

  <p>
    <strong>FUNCIONÁRIOS:</strong>
    <ul>
      <% equipe.funcionarios.each do |funcionario| %>
          <li><%= funcionario.nome %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>DESCRIÇÃO</strong>
    <%= equipe.descricao %>
  </p>

  <%= link_to "Editar", edit_equipe_path(equipe), class: "btn btn-primary" %>
  <%= button_to "Deletar", equipe, method: :delete, class: "btn btn-danger mt-1 " %> 
      
</div>

app/views/equipes/_form.html.erb
<%= form_with(model: equipe, local: true) do |form| %>
  <% if equipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(equipe.errors.count, "error") %> prohibited this equipe from being saved:</h2>

      <ul>
        <% equipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
  <%= form.label :descricao, style: "display: block" %>
  <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/equipes/edit.html.erb
<div class="design">

<h1>EDITAR EQUIPE</h1>

<%= render "form", equipe: @equipe %>

<div>
  

  <%= link_to "Voltar", equipes_path, class:"btn btn-warning voltar" %>

</div>

</div>

app/views/equipes/index.html.erb
<div class="design">
<p style="color: green"><%= notice %></p>

<h1>EQUIPES</h1>

<div id="equipes">
  <% @equipes.each do |equipe| %>
    <%= render equipe %>
  <% end %>
</div>
<%= link_to "Cadastrar equipe", new_equipe_path, class: "btn btn-success btn-cadastro" %>

</div>

app/views/equipes/new.html.erb
<div class="design">
<h1>CADASTRAR EQUIPE</h1>

<%= render "form", equipe: @equipe %>

  <%= link_to "Voltar", equipes_path, class:"btn btn-warning" %>

</div>

app/views/equipes/show.html.erb
<div>
<p style="color: green"><%= notice %></p>


  <%= render @equipe %>


<div>
  <%= link_to "Voltar", equipes_path, class:"btn btn-warning mr-2 d-inline"%>
</div>  
  
</div>

app/views/parts/_form.html.erb
<%= form_with(model: part) do |form| %>
  <% if part.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade, min: 0, step: 1 %>
  </div>

  <div>
    <%= form.label :preco, style: "display: block" %>
    <%= form.text_field :preco, min: 0, step: 1 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<div id="<%= dom_id part %>" class="design-info">
  <p>
    <strong>Nome:</strong>
    <%= part.nome %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= part.quantidade %>
  </p>

  <p>
    <strong>Preco:</strong>
    <%= part.preco %>
  </p>

  <%= link_to "Editar", edit_part_path(part), class: "btn btn-primary" %>
  <%= button_to "Deletar", part, method: :delete, class: "btn btn-danger mt-1 " %>

</div>

app/views/parts/edit.html.erb
<div class="design">
<h1>EDITAR PEÇA</h1>

<%= render "form", part: @part %>

<div>

    <%= link_to "Voltar", parts_path, class: "btn btn-warning"%>

</div>
</div>

app/views/parts/index.html.erb
<div class="design">
<p style="color: green"><%= notice %></p>

<h1>PEÇAS</h1>

<div id="parts">
  <% @parts.each do |part| %>
    <%= render part %>
  <% end %>
</div>

<%= link_to "Cadastrar peça", new_part_path, class: "btn btn-success btn-cadastro" %>

</div>

app/views/parts/new.html.erb
<div class="design">
<h1>CADASTRAR PEÇA</h1>

<%= render "form", part: @part %>

  <%= link_to "Voltar", parts_path, class: "btn btn-warning" %>

</div>

app/views/parts/show.html.erb
<div>
<p style="color: green"><%= notice %></p>

<%= render @part %>

<div>

  <%= link_to "Voltar", parts_path, class: "btn btn-warning" %>

</div>