config/routes.rb
Rails.application.routes.draw do
  resources :ordem_servicos
  resources :equipes
  resources :veiculos
  resources :funcionarios
  resources :parts
  resources :servicos
  resources :clientes

  devise_for :users
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    get '/users/sign_in', to: 'devise/sessions#new'
    post '/users/sign_in', to: 'devise/sessions#create'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  get 'home/dashboard'
  root 'home#dashboard'

  resources :ordem_servicos do
    member do
      post 'concluir'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :ordem_servicos, dependent: :destroy
    has_many :veiculos, dependent: :destroy

    
  def self.total_clientes
    count
  end
  
end

app/models/equipe.rb
class Equipe < ApplicationRecord
    has_many :funcionarios, dependent: :destroy
    has_many :ordem_servicos, dependent: :destroy
end
  

app/models/funcionario.rb
class Funcionario < ApplicationRecord
    belongs_to :equipe

    def self.total_funcionarios
        count
    end

end

app/models/ordem_servico.rb
class OrdemServico < ApplicationRecord
    belongs_to :veiculo
    belongs_to :cliente
    belongs_to :equipe
    belongs_to :servico
    belongs_to :part

    
    
    def valor_total
        part.preco + servico.valor
    end

    def self.total_ordens_concluidas
        where(concluida: true).count
    end

end

app/models/part.rb
class Part < ApplicationRecord

    has_many :ordem_servicos, dependent: :destroy

    def self.valor_total_em_estoque
        Part.sum('preco * quantidade')
    end
    def self.total_em_estoque
        Part.sum(:quantidade)
    end
end

app/models/servico.rb
class Servico < ApplicationRecord
    has_many :ordem_servicos, dependent: :destroy

    def self.total_servicos
        count
    end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
    belongs_to :cliente
    has_many :ordem_servicos, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    
    @quantidade_em_estoque = Part.total_em_estoque
    @total_clientes = Cliente.total_clientes
    @total_servicos = Servico.total_servicos
    @total_ordens_concluidas = OrdemServico.total_ordens_concluidas
    @total_funcionarios = Funcionario.total_funcionarios
    @valor_total_em_estoque = Part.valor_total_em_estoque

  end
end

app/controllers/ordem_servicos_controller.rb
class OrdemServicosController < ApplicationController
  before_action :set_ordem_servico, only: %i[ show edit update destroy ]

  def concluir
    @ordem_servico = OrdemServico.find(params[:id])
    @ordem_servico.update(concluida: true) unless @ordem_servico.concluida?

    redirect_to @ordem_servico, notice: 'Ordem de serviço concluída com sucesso.'
  end

  # GET /ordem_servicos or /ordem_servicos.json
  def index
    @ordem_servicos = OrdemServico.all
    @equipes = Equipe.all
    @veiculos = Veiculo.all
    @clientes = Cliente.all
    @servicos = Servico.all
    @parts = Part.all
    @ordem_servico = OrdemServico.new
    
  end

  # GET /ordem_servicos/1 or /ordem_servicos/1.json
  def show
  end

  # GET /ordem_servicos/new
  def new
    @ordem_servico = OrdemServico.new
  end

  # GET /ordem_servicos/1/edit
  def edit
  end

  # POST /ordem_servicos or /ordem_servicos.json
  def create
    @ordem_servico = OrdemServico.new(ordem_servico_params)
    @ordem_servico.cliente = Cliente.find(params[:ordem_servico][:cliente_id])
    @ordem_servico.veiculo = Veiculo.find(params[:ordem_servico][:veiculo_id])
    @ordem_servico.equipe = Equipe.find(params[:ordem_servico][:equipe_id])
    @ordem_servico.part = Part.find(params[:ordem_servico][:part_id])
    @ordem_servico.servico = Servico.find(params[:ordem_servico][:servico_id])
  
    respond_to do |format|
      if @ordem_servico.save

        @ordem_servico.part.decrement!(:quantidade)

        if @ordem_servico.part.quantidade.zero?
          @ordem_servico.update(part: nil)
        end

        format.html { redirect_to ordem_servico_url(@ordem_servico), notice: "Ordem servico was successfully created." }
        format.json { render :show, status: :created, location: @ordem_servico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ordem_servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordem_servicos/1 or /ordem_servicos/1.json
  def update
    respond_to do |format|
      if @ordem_servico.update(ordem_servico_params)
        format.html { redirect_to ordem_servico_url(@ordem_servico), notice: "Ordem servico was successfully updated." }
        format.json { render :show, status: :ok, location: @ordem_servico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ordem_servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordem_servicos/1 or /ordem_servicos/1.json
  def destroy
    @ordem_servico.destroy!

    respond_to do |format|
      format.html { redirect_to ordem_servicos_url, notice: "Ordem servico was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordem_servico
      @ordem_servico = OrdemServico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  
    def ordem_servico_params
      params.require(:ordem_servico).permit(:cliente_id, :veiculo_id, :equipe_id, :conclusao, :servico_id, :part_id, :created_at, :updated_at)
    end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]

  # GET /parts or /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1 or /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts or /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to part_url(@part), notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1 or /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to part_url(@part), notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1 or /parts/1.json
  def destroy
    @part.destroy!

    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:nome, :quantidade, :preco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ordem_servicos_helper.rb
module OrdemServicosHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ordem_servicos/_form.html.erb
<%= form_with(model: ordem_servico) do |form| %>
  <% if ordem_servico.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ordem_servico.errors.count, "error") %> prohibited this ordem_servico from being saved:</h2>
      <ul>
        <% ordem_servico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.collection_select(:cliente_id, Cliente.all, :id, :nome, { prompt: 'Selecione o cliente' }) %>
  </div>

  <div>
    <%= form.label :veiculo_id, style: "display: block" %>
    <%= form.collection_select(:veiculo_id, Veiculo.all, :id, :modelo, { prompt: 'Selecione o veiculo' }) %>
  </div>

  <div>
    <%= form.label :equipe_id, style: "display: block" %>
    <%= form.collection_select(:equipe_id, Equipe.all, :id, :nome, { prompt: 'Selecione a equipe' }) %>
  </div>

  <div>
    <%= form.label :part_id, style: "display: block" %>
    <%= form.collection_select(:part_id, Part.all, :id, :nome, { prompt: 'Selecione a Peça' }) %>
  </div>

  <div>
    <%= form.label :servico_id, style: "display: block" %>
    <%= form.collection_select(:servico_id, Servico.all, :id, :nome, { prompt: 'Selecione o funcionario' }) %>
  </div>

  <div>
    <%= form.label :conclusao, style: "display: block" %>
    <%= form.date_field :conclusao %>
  </div>

  <div>
    <%= form.submit %>
  </div>


<% end %>

app/views/ordem_servicos/_ordem_servico.html.erb
<div id="<%= dom_id ordem_servico %>"  class="design-info">

  <p>
    <strong>Cliente:</strong>
    <%= ordem_servico.cliente.nome %>
  </p>

  <p>
    <strong>Veiculo:</strong>
    <%= ordem_servico.veiculo.modelo %>
  </p>

  <p>
    <strong>Equipe:</strong>
    <%= ordem_servico.equipe.nome %>
  </p>

  <p>
  <strong>Data de Criação:</strong>
  <%= ordem_servico.created_at %>
  </p>

  <p>
    <strong>Conclusao:</strong>
    <%= ordem_servico.conclusao %>
  </p>

  <p>
    <strong>Peça:</strong>
    <%= ordem_servico.part.nome %>
  </p>

  <p>
    <strong>Servico:</strong>
    <%= ordem_servico.servico.nome %>
  </p>

  <p>
  <strong>Valor Total:</strong>
    <%= ordem_servico.valor_total %>
  </p>


  <% if ordem_servico.id.present? %>
    
    <% if ordem_servico.concluida? %>
      <span class="btn btn-success disabled">Concluida</span>
    <% else %>
      <%= button_to 'Concluir Ordem de Serviço', concluir_ordem_servico_path(ordem_servico), method: :post, class: "btn btn-success mb-1" %>
    <% end %>
    
  <% end %>
  <%= link_to "Editar", edit_ordem_servico_path(ordem_servico), class: "btn btn-primary" %>
  <%= button_to "Deletar", ordem_servico, method: :delete, class: "btn btn-danger mt-1 " %>

</div>

app/views/ordem_servicos/edit.html.erb
<div class="design">
<h1>EDITAR ORDEM DE SERVIÇO</h1>

<%= render "form", ordem_servico: @ordem_servico %>

<div>
  
  <%= link_to "Voltar", ordem_servicos_path, class: "btn btn-warning voltar" %>
  
</div>
</div>

app/views/ordem_servicos/index.html.erb
<div class="design">
<p style="color: green"><%= notice %></p>

<h1>ORDENS</h1>

<div id="ordem_servicos">
  <% @ordem_servicos.each do |ordem_servico| %>
    <%= render ordem_servico %>
  <% end %>
</div>

<%= link_to "Cadastrar ordem servico", new_ordem_servico_path, class: "btn btn-success btn-cadastro" %>

</div>

app/views/ordem_servicos/new.html.erb
<div class="design">
<h1>CADASTRAR ORDEM DE SERVIÇO</h1>

<%= render "form", ordem_servico: @ordem_servico %>

    <%= link_to "Voltar", ordem_servicos_path, class: "btn btn-warning" %>

</div>

app/views/ordem_servicos/show.html.erb
<div>
<p style="color: green"><%= notice %></p>

<%= render @ordem_servico %>

<div>

    <%= link_to "Voltar", ordem_servicos_path, class: "btn btn-warning" %>

</div>