config/routes.rb
Rails.application.routes.draw do
  resources :ordem_servicos
  resources :equipes
  resources :veiculos
  resources :funcionarios
  resources :parts
  resources :servicos
  resources :clientes

  devise_for :users
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    get '/users/sign_in', to: 'devise/sessions#new'
    post '/users/sign_in', to: 'devise/sessions#create'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  get 'home/dashboard'
  root 'home#dashboard'

  resources :ordem_servicos do
    member do
      post 'concluir'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :ordem_servicos, dependent: :destroy
    has_many :veiculos, dependent: :destroy

    
  def self.total_clientes
    count
  end
  
end

app/models/equipe.rb
class Equipe < ApplicationRecord
    has_many :funcionarios, dependent: :destroy
    has_many :ordem_servicos, dependent: :destroy
end
  

app/models/funcionario.rb
class Funcionario < ApplicationRecord
    belongs_to :equipe

    def self.total_funcionarios
        count
    end

end

app/models/ordem_servico.rb
class OrdemServico < ApplicationRecord
    belongs_to :veiculo
    belongs_to :cliente
    belongs_to :equipe
    belongs_to :servico
    belongs_to :part

    
    
    def valor_total
        part.preco + servico.valor
    end

    def self.total_ordens_concluidas
        where(concluida: true).count
    end

end

app/models/part.rb
class Part < ApplicationRecord

    has_many :ordem_servicos, dependent: :destroy

    def self.valor_total_em_estoque
        Part.sum('preco * quantidade')
    end
    def self.total_em_estoque
        Part.sum(:quantidade)
    end
end

app/models/servico.rb
class Servico < ApplicationRecord
    has_many :ordem_servicos, dependent: :destroy

    def self.total_servicos
        count
    end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
    belongs_to :cliente
    has_many :ordem_servicos, dependent: :destroy
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]

  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
    @equipes = Equipe.all
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)
    @funcionario.equipe = Equipe.find(params[:funcionario][:equipe_id])

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully created." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully updated." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy!

    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :funcao, :equipe_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    
    @quantidade_em_estoque = Part.total_em_estoque
    @total_clientes = Cliente.total_clientes
    @total_servicos = Servico.total_servicos
    @total_ordens_concluidas = OrdemServico.total_ordens_concluidas
    @total_funcionarios = Funcionario.total_funcionarios
    @valor_total_em_estoque = Part.valor_total_em_estoque

  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]

  # GET /parts or /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1 or /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts or /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to part_url(@part), notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1 or /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to part_url(@part), notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1 or /parts/1.json
  def destroy
    @part.destroy!

    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:nome, :quantidade, :preco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ordem_servicos_helper.rb
module OrdemServicosHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :Especialidade, style: "display: block" %>
    <%= form.text_field :funcao %>
  </div>

  <div>
    <%= form.label :equipe_id, style: "display: block" %>
    <%= form.collection_select(:equipe_id, Equipe.all, :id, :nome, { prompt: 'Selecione a equipe' }) %>
  </div>


  <div>
    <%= form.submit %>
  </div>


<% end %>

app/views/funcionarios/_funcionario.html.erb
<div id="<%= dom_id funcionario %>"class="design-info">
  <p>
    <strong>Nome:</strong>
    <%= funcionario.nome %>
  </p>

  <p>
    <strong>Especialidade:</strong>
    <%= funcionario.funcao %>
  </p>

  <p>
    <strong>Equipe:</strong>
    <%= funcionario.equipe.nome %>
  </p>

  <%= link_to "Editar", edit_funcionario_path(funcionario), class: "btn btn-primary" %>
  <%= button_to "Deletar", funcionario, method: :delete, class: "btn btn-danger mt-1 " %> 

</div>

app/views/funcionarios/edit.html.erb
<div class="design">
<h1>EDITAR FUNCIONÁRIO</h1>

<%= render "form", funcionario: @funcionario %>

<div>

  <%= link_to "Voltar", funcionarios_path, class: "btn btn-warning voltar" %>

</div>
</div>

app/views/funcionarios/index.html.erb
<div class="design">
<p style="color: green"><%= notice %></p>

<h1>FUNCIONÁRIOS</h1>

<div id="funcionarios">
  <% @funcionarios.each do |funcionario| %>
    <%= render funcionario %>
  <% end %>
</div>


<%= link_to "Cadastrar funcionario", new_funcionario_path, class: "btn btn-success btn-cadastro"%>

</div>

app/views/funcionarios/new.html.erb
<div class="design">
<h1>CADASTRAR FUNCIONÁRIO</h1>

<%= render "form", funcionario: @funcionario %>

  <%= link_to "Voltar", funcionarios_path, class: "btn btn-warning" %>

</div>

app/views/funcionarios/show.html.erb
<div>
<p style="color: green"><%= notice %></p>

<%= render @funcionario %>

<div>

  <%= link_to "Voltar", funcionarios_path, class: "btn btn-warning" %>

</div>
</div>