config/routes.rb
Rails.application.routes.draw do
  resources :ordem_servicos
  resources :equipes
  resources :veiculos
  resources :funcionarios
  resources :parts
  resources :servicos
  resources :clientes

  devise_for :users
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    get '/users/sign_in', to: 'devise/sessions#new'
    post '/users/sign_in', to: 'devise/sessions#create'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  get 'home/dashboard'
  root 'home#dashboard'

  resources :ordem_servicos do
    member do
      post 'concluir'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :ordem_servicos, dependent: :destroy
    has_many :veiculos, dependent: :destroy

    
  def self.total_clientes
    count
  end
  
end

app/models/equipe.rb
class Equipe < ApplicationRecord
    has_many :funcionarios, dependent: :destroy
    has_many :ordem_servicos, dependent: :destroy
end
  

app/models/funcionario.rb
class Funcionario < ApplicationRecord
    belongs_to :equipe

    def self.total_funcionarios
        count
    end

end

app/models/ordem_servico.rb
class OrdemServico < ApplicationRecord
    belongs_to :veiculo
    belongs_to :cliente
    belongs_to :equipe
    belongs_to :servico
    belongs_to :part

    
    
    def valor_total
        part.preco + servico.valor
    end

    def self.total_ordens_concluidas
        where(concluida: true).count
    end

end

app/models/part.rb
class Part < ApplicationRecord

    has_many :ordem_servicos, dependent: :destroy

    def self.valor_total_em_estoque
        Part.sum('preco * quantidade')
    end
    def self.total_em_estoque
        Part.sum(:quantidade)
    end
end

app/models/servico.rb
class Servico < ApplicationRecord
    has_many :ordem_servicos, dependent: :destroy

    def self.total_servicos
        count
    end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
    belongs_to :cliente
    has_many :ordem_servicos, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    
    @quantidade_em_estoque = Part.total_em_estoque
    @total_clientes = Cliente.total_clientes
    @total_servicos = Servico.total_servicos
    @total_ordens_concluidas = OrdemServico.total_ordens_concluidas
    @total_funcionarios = Funcionario.total_funcionarios
    @valor_total_em_estoque = Part.valor_total_em_estoque

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OFICINA</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head> 
  <body>
  <header>
    <div class="row-header">
      <div class="col-md-12 d-flex align-items-center justify-content-end p-2">

      <div class="nome-perfil mt-4 align-self-center">
        <% if user_signed_in? %>
          <p style="color: white; font-size:1vw; font-family: Arial, Helvetica, sans-serif;margin-right: 10px;">
          Olá, <%= current_user.email %>
          </p>
        <% end %>
      </div>

      <div class="mt-2 align-self-center">  
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          <% else %>
            <%= link_to 'Login', new_user_session_path, class: "btn btn-success" %>
          <% end %>
      </div>


      </div>
    </div>
  </header>

  <nav class="navbar navbar-expand-lg navbar-light bg-black col-md-12 text-white">
    <div class="navbar-nav p-2 d-flex justify-content-between" style="margin-left: 5vw;">
      <div class="navbar-t px-5 mt-3 flex-grow-1">
        <%= link_to root_path, class: "nav-item nav-link" do %>
          <p style="color: white; font-size:1.1vw; font-family: Arial, Helvetica, sans-serif;">DASHBOARD</p>
        <% end %>
      </div>

      <div class="px-4 mt-3 flex-grow-1">
        <%= link_to clientes_path, class: "nav-item nav-link" do %>
          <p  style="color: white; font-size:1.1vw; font-family: Arial, Helvetica, sans-serif;">CLIENTES</p>
        <% end %>
      </div>

      <div class="px-4 mt-3 flex-grow-1">
        <%= link_to veiculos_path, class: "nav-item nav-link" do %>
          <p style="color: white; font-size:1.1vw; font-family: Arial, Helvetica, sans-serif;">VEICULOS</p>    
        <% end %>
      </div>

      <div class="px-4 mt-3 flex-grow-1">
        <%= link_to servicos_path, class: "nav-item nav-link" do %>
          <p style="color: white; font-size:1.1vw; font-family: Arial, Helvetica, sans-serif;">SERVIÇOS</p>    
        <% end %>
      </div>
      
      <div class="px-4 mt-3 flex-grow-1">
        <%= link_to parts_path, class: "nav-item nav-link" do %>
          <p style="color: white; font-size:1.1vw; font-family: Arial, Helvetica, sans-serif;">PEÇAS</p>    
        <% end %>
      </div>

      <div class="px-4 mt-3 flex-grow-1">
        <%= link_to ordem_servicos_path, class: "nav-item nav-link" do %>
          <p style="color: white; font-size:1.1vw; font-family: Arial, Helvetica, sans-serif;">ORDENS</p>    
        <% end %>
      </div>

      <div class="px-4 mt-3 flex-grow-2">
        <%= link_to funcionarios_path, class: "nav-item nav-link" do %>
          <p style="color: white; font-size:1.1vw; font-family: Arial, Helvetica, sans-serif;">FUNCIONÁRIOS</p>    
        <% end %>
      </div>

      <div class="px-4 mt-3 flex-grow-2">
        <%= link_to equipes_path, class: "nav-item nav-link" do %>
          <p style="color: white; font-size:1.1vw; font-family: Arial, Helvetica, sans-serif;">EQUIPES</p>    
        <% end %>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</html>